jonytoast/MeowMatch

index.html
added main section color can be added if wanted and writing and the logo
=> main section added

assets/css/style.css, index.html
Hey Guys I've updated the html a little more and added some scrolling function with html and css!
I will continue to populate the html content tomorrow!
=> added sections and scrolling function with css

index.html
=> finished Facts section

assets/css/style.css, index.html
Added color variables in css and made some changes to background color and button behavior
=> Html update

index.html
added small fixes to the entire site
=> Fixes three

assets/css/style.css, index.html
=> css update

assets/css/style.css, index.html
=> added css styling

assets/css/style.css, assets/js/script.js, index.html
Hey guys, I added a cat charity donation API to the JS and added a HTML for it as well. Please review and merge when you can! Thanks!
=> added new API, html section, and css styling

assets/js/script.js
Hey guys sorry for the trouble, but git was giving me issues so I had to manually merge benji's codes with the previous version. Please merge this for me - I fixed typo I created when manually merging the branches! Thanks!
=> fixed merge typo

assets/js/script.js
Hey Guys I'm still in the middle of trying to finish up the remove charity from save list function. Will finish up soon. But for now, please merge for me so we all have the most updated codes.
=> Fred branch

assets/js/script.js
Hey guys sorry it took a while but I finally figured out how to remove charity from saved list. Please review and merge for me. Thanks!
=> remove charity from saved list function complete

assets/js/script.js
Hey guys I fixed the email bug so that only actual email links will be styled
=> fixed email bug

README.md, assets/css/style.css
Hey Guys I added more content to README
=> updated README

assets/css/style.css, assets/js/script.js, index.html
add the button to all cards when it is generated to allow user to save
=> added button to cat card

assets/css/style.css, assets/js/script.js, index.html
Hey guys I did some updates on CSS and JS - just minor things mostly for aesthetics. Please take a look and merge for me. Thanks!
=> css updates

index.html
Hey guys I moved the cat-fact section up the html structure so it doesn't interfere with the automatic scroll-down function of cat-search button. Please merge. Thanks!
=> html structure tweak 

assets/css/style.css, assets/js/script.js, index.html
Hey Guys I'm making progress on the save-cat button. Need to work on the remove-cat function and tweak the display later. But for now please review and merge for me. Thanks!
=> working on save-cat function

assets/css/style.css, assets/js/script.js, index.html
=> fixed email link bug

assets/css/style.css, assets/js/script.js, index.html
Hey guys are cleaned up the codes and added comments so everything looks cleaner!
=> cleaned up codes and added comments to html css and js

README.md, assets/css/style.css, assets/js/script.js, index.html
Hey guys one final thing I swear - I added the "alt" attributes to images and gif's so it's the website is more accessible
=> added alt attributes to images and gifs
